// Generated by CoffeeScript 1.10.0
(function() {
  var Bouncer, Compiler, VERBOSE, fs,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  fs = require('fs');

  Compiler = require('metaserve/lib/compiler');

  VERBOSE = process.env.METASERVE_VERBOSE || false;

  Bouncer = (function(superClass) {
    extend(Bouncer, superClass);

    function Bouncer() {
      return Bouncer.__super__.constructor.apply(this, arguments);
    }

    Bouncer.prototype.compile = function(bounced_filename, cb) {
      if (VERBOSE) {
        console.log('[Bouncer] Serving bounced ' + bounced_filename);
      }
      return fs.readFile(bounced_filename, 'utf-8', cb);
    };

    Bouncer.prototype.shouldCompile = function(bounced_filename) {
      var enabled;
      enabled = this.options.enabled != null ? this.options.enabled : true;
      return function(req, res, next) {
        return enabled && (req.headers['x-skip-bouncer'] == null);
      };
    };

    return Bouncer;

  })(Compiler);

  module.exports = function(options) {
    if (options == null) {
      options = {};
    }
    return new Bouncer(options);
  };

}).call(this);
