// Generated by CoffeeScript 1.12.4
(function() {
  var VERBOSE, fs;

  fs = require('fs');

  VERBOSE = process.env.METASERVE_VERBOSE || false;

  module.exports = {
    ext: '+bounced',
    compile: function(filename, config, context, cb) {
      if (VERBOSE) {
        console.log('[Bouncer.compile] Serving bounced ' + filename);
      }
      return fs.readFile(filename, 'utf-8', cb);
    },
    shouldCompile: function(filename, config, context) {
      var enabled, ref, ref1;
      enabled = config.enabled != null ? config.enabled : true;
      return enabled && (((ref = context.req) != null ? (ref1 = ref.headers) != null ? ref1['x-skip-bouncer'] : void 0 : void 0) == null);
    }
  };

}).call(this);
